#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

COMMIT=`git log --pretty=oneline -1 | awk '{ print $1 }'`
DATE=`date --rfc-3339=seconds`
sed -e "s/COMMIT/$COMMIT/" -e "s/DATE/$DATE/" < inline-more/VERSION.git > inline-more/VERSION
: Nothing
